### ISSUE TITLE
Debugging doesn't start 

### ISSUE THREAD

**Issue by shaunenslin** [gwomacks/php-debug#164]
Hi there
My debugging was working first time round, but I have not been able to get it working since.
I have a vagrant server and have mapped port forwarding for port 9001 to use for xdebug.
I have also tried adding xdebug_break(); to my code, but has not helped.

I am hoping someone has an idea on this.

My php.ini is as follows:
```
zend_extension=/usr/lib/php5/20121212/xdebug.so
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_host=192.168.10.117
xdebug.remote_connect_back=0
xdebug.remote_port=9001
xdebug.remote_autostart=On
xdebug.remote_mode=req
xdebug.remote_log=/var/rapidapi/xdebug.log
```

My config.cson has remote paths mapped as below:
ps. IP addresses, Remote/Local paths are correct.

```
"php-debug":
    PathMaps: [
      "/var/www/html/rapidapi;/Users/shaun/git/rapidapi"
    ]
    ServerPort: 9001
```

I start PHP-Debug in Atom and it says Listening on port 9001 as attached.
When running the PHP page from PostMan, phpdebug does not connect and in xdebug logs, I end up with below. It seems to connect, but then seems to disconnect.

```
Log opened at 2016-05-22 15:03:48
I: Connecting to configured address/port: 192.168.10.117:9001.
I: Connected to client. :-)
-> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///var/www/html/rapidapi/dynamodb.php" language="PHP" xdebug:language_vers$

-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" status="break" reason="ok"><xdebug:message filename="file:///var/www/html/rapidapi/d$

-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" status="stopping" reason="ok"></response>

Log closed at 2016-05-22 15:03:50 
```
<img width="1676" alt="screen shot 2016-05-22 at 5 15 48 pm" src="https://cloud.githubusercontent.com/assets/15326780/15454716/e1361814-2040-11e6-850b-5cbced6b367f.png">

**Comment by marod424** [comment]
If your local path is on a Windows machine try the following:

`\\Users\\shaun\\git\\rapidapi`

Or you may need an absolute path:

`C:\\Users\\shaun\\git\\rapidapi`

If you set a breakpoint in Atom then the xdebug log should show the breakpoint with the file path.  Make sure that file path is correct.

**Comment by cchamplin** [comment]
No comments on this in several months. Closing, reopen if needed.

**Comment by jigarius** [comment]
I wanted to map remote path `/drupal/site` to the `site` directory in the project. I set the path configuration to `/drupal/site;site` and it works when I add a `xdebug_break()` in the file. But as soon as I remove the `xdebug_break()`, no breakpoints work!

Investigating the path thing mentioned above, I figured I will have to mention the entire local path like `/home/me/path/to/project/drupal/site`. Doing so makes things work, however, it would be better if one could specify relative paths too. For Example, `/drupal/site;site`, which would map the remote path to the `site` directory in the project root, which would make life much easier. Just a recommendation because IDEs like PHP Storm and NetBeans do not even require a path mapping to be specified, so adding support for such relative paths (or maybe auto-detection of path mapping in some way) will make this plugin more competetive.
