### ISSUE TITLE
Doesn't "Continue" to a breakpoint

### ISSUE THREAD

**Issue by mrthebob** [gwomacks/php-debug#225]
When I set a breakpoint and then refresh the page in the browser, the debug starts (good).  I then press "Continue", and it doesn't go to my first breakpoint.  Instead it pauses at some arbitrary point in the code.  It doesn't matter how many times I step over or out or continue or whatever, it keeps opening new files at arbitrary points.

**Comment by cgalvarez** [comment]
@mrthebob When the package stops at a location with no set breakpoint, it is often due to a PHP error. Have you check the PHP console (of this same package) or your PHP logs? Don't trust your browser, sometimes the errors just simply are not shown.

Besides, I don't need to click on "Continue" to go to my first breakpoint. I just open first the panel `PHP Debug` inside Atom, then navigate to the desired page, and it should automatically stop on your first breakpoint. No need to click on "Continue". Please, provide a reproducible steps list on how are you testing.

Maybe the debugger stops on an error encountered first before reaching your breakpoint, and that's why you need to click on "Continue", and after clicking it, your code breaks, so never reaches that breakpoint.
