### ISSUE TITLE
Php-debug do not start

### ISSUE THREAD

**Issue by egoriy33** [gwomacks/php-debug#233]
Good day!
I have just installed php-debug package and is having problems with the very beginning
I fullfilled all the instructions listed in package doc([here](https://atom.io/packages/php-debug))
And here you are - I stuck!
All buttons of debugger are disabled not clickable.

**Comment by StAmourD** [comment]
Does your script appear to be hung or does it run all the way to the end? If it appears hung try pressing `alt-f5` shortcut for 'Continue', and see if it'll run to your break point.

I've noticed this stop on first line on my setup since 0.2.5 release but haven't had a chance to investigate it. The symptoms are similar to what you have here, the buttons are grayed out, but the shortcut keys for the buttons work.
