### ISSUE TITLE
Step In Opens File in Wrong Pane

### ISSUE THREAD

**Issue by imperez** [gwomacks/php-debug#62]
When I step into a function that's associated to a different file it opens in the same Pane as the Debugging window. Is there a way to make it open in the main or first Pane?

**Comment by remon-georgy** [comment]
Yes, I can reproduce that consistently. I'm fairly certain is used to work properly in earlier versions, though.

**Comment by driskell** [comment]
I think it's because when you click Step In, you've activated the bottom panel split where the Debugger tab is, and so the file opens in the currently active panel next to it.

Have a look at my PR #96 - I was experimenting moving the Debugger to a bottom panel so files always open in the right place, and it makes it easier to open/close too with a status bar button. The maintainer hasn't had a look yet but I'm looking for feedback on if it's a good approach or not.

**Comment by cchamplin** [comment]
@driskell's changes have been added to the latest release.
